config/routes.rb
Rails.application.routes.draw do
  root 'links#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links
    end
  end

  scope controller: :users do
    post 'users/create' => :create, as: :new_user
    get 'users/sign_up' => :new, as: :sign_up
  end

  scope controller: :links do
    post '/dashboard/link/new' => :create
    get '/dashboard' => :show, as: :dashboard
    post '/dashboard/link/:id/update' => :update
    delete '/dashboard/:id/link' => :destroy
    patch '/dashboard/link/:id/activate' => :toggle_activate
    get '/:slug' => :redirect
    post '/auth_token' => :generate_key
    get '/link/inactive' => :inactive
    get '/link/deleted' => :deleted
  end

  scope controller: :sessions do
    get '/users/sign_in' => :new, as: :sign_in
    get '/users/sign_out' => :destroy, as: :sign_out
    post '/users/sign_in' => :create, as: :log_in
  end
end

app/views/layouts/_flash.html.erb
<% unless flash.blank? %>
  <div id="notice_wrapper" role="alert">
    <p>
      <%= flash[:notice] || flash[:alert] %>
    </p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
         data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "TurboUrl", root_path, class: "navbar-brand text-white" %>
      </div>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle text-white text-lg" data-toggle="dropdown"
             role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user"></span>
              &nbsp;
              <%= current_user.first_name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", sign_out_path %></li>
            </ul>
          </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', sign_in_path, class: 'btn text-white' %>
            </li>
            <li>
            <%= link_to 'Sign Up', sign_up_path,
             class: 'btn btn-transparent' %>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400|Roboto:300,400,700" rel="stylesheet">
</head>
<body>

  <%= render 'layouts/flash' %>

  <%= render 'layouts/navbar' %>

  <div class="container-fluid">
    <%= yield %>
  </div>
  
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard | <%= current_user.first_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400|Roboto:300,400,700" rel="stylesheet">
</head>
<body>

  <%= render 'layouts/flash' %>

  <nav class="navbar navbar-fixed-top bg-dark-blue">
    <%= render 'shared/navbar' %>
  </nav>

  <div class="container-fluid">
  <div class="jumbotron bg-light-blue dashboard-jumbotron">
    <div class="col-lg-9 col-lg-offset-2 clear_top">
      <%= form_tag(:controller => 'links', :action => 'create') do %>
        <div class="form-group">
          <%= url_field_tag 'link[given_url]', nil, class: 'form-control input-lg',
           placeholder: 'Paste the long ugly URL...', required: 'true' %>
        </div>
        <div class="form-group">
          <%= text_field_tag 'link[slug]', nil, class: 'form-control input-lg',
           placeholder: 'Type a fancy text you prefer' %>
        </div>
        <div>
            <%= submit_tag "CREATE LINK", options = { class: "btn btn-primary btn-lg col-lg-6 col-lg-offset-3" } %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="well">
    API KEY: &nbsp;&nbsp;
    <% if current_user.auth_token.blank? %>
      <%= link_to 'Generate API KEY', { controller: 'links', action: 'generate_key' }, method: :post, class: 'btn btn-primary' %>
    <% else %>
      <%= current_user.auth_token %>
    <% end %>
  </div>
  <% if current_user.errors.any? %>
  <%= current_user.errors.full_message.to_sentence %>
  <% end %>
    <%= yield %>
  </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.12/clipboard.min.js"></script>
</body>
</html>